### ISSUE TITLE
Creating All the Initial Tasks / User Stories / Issues for Spring Planning

### ISSUE THREAD

**Issue by iamStephenE** [Android-Dev-Group-7/Simu-Coins#3]
- [x] Create item for each user story and convert them into issues 
- [x] Assign each issue to a partner/teammate
- [x] Select the order in which is issuse is prioritized and assign each issue to a milestone

**Comment by tpatel29** [comment]
Sprint 1
Starter code - Gregory
Project Config - Austin
Login UI - Stephen
Login Functionality - Tejkumar

Sprint 2
Register UI - Stephen
Register Functionality - Tejkumar
Navigation bar - Gregory / Austin

Sprint 3
Dashboard UI - Stephen
Dashboard Functionality - Tejkumar
Profile UI - Gregory
Profile Functionality - Austin

Sprint 4
Search UI - Stephen
Search Functionality - Tejkumar
Trans UI - Gregory
Trans Functionality - Austin

Sprint 5
Selling UI - Stephen
Selling Functionality - Tejkumar
Buying UI - Gregory
Buying Functionality - Austin
